Lesson 17
askrynnikov/tutu pull request #6
Opened 2016-12-21 06:29 UTC by askrynnikov

2016-12-21 07:24 UTC, askrynnikov commented on app/views/searches/show.html.erb
> +              <%= form_tag new_ticket_path, method: :get do %>
Эта форма перестает рендерится если ее поместить внутрь формы поиска.(<% end %> с 18 строки перенести в конец файла).  Какие изменения в код необходимо внести что-бы она заработала и как вложенная?

2016-12-21 07:53 UTC, askrynnikov commented on app/helpers/cars_helper.rb
> +  class CarsFormBuilder < ActionView::Helpers::FormBuilder
Женя по твоему совету убрал CarsFormBuilder в `app/helpers/cars_helper/cars_form_builder.rb` и в `app/views/cars/_form.html.erb` хочу оставить так `:builder => CarsFormBuilder` что нужно сделать? Если можно - ссылки на лучшие практики?

В [stackoverflow](http://stackoverflow.com/a/6546533/5013769) описан мой первый вариант и вариант с добавлением `config.load_paths += %W( #{RAILS_ROOT}/app/builders )`. В Rails 5 есть стандартное место для пользовательских FormBuilder-ов?

2016-12-21 20:49 UTC, psylone requested changes

2016-12-21 20:49 UTC, psylone commented on app/controllers/railway_stations_controller.rb
>      params.require(:railway_station).permit(:title)
По-моему, здесь чего-то не хватает.

2016-12-21 20:49 UTC, psylone commented on config/routes.rb
> +    resources :cars, shallow: true
Проверь создание вагонов.

2016-12-21 20:49 UTC, psylone commented on app/views/searches/show.html.erb
> +              <%= form_tag new_ticket_path, method: :get do %>
Да, потому что вложенные формы не допускаются согласно спецификации HTML.

2016-12-21 20:49 UTC, psylone commented on app/controllers/tickets_controller.rb
> +    @ticket = Ticket.new(train_id: params[:train_id], start_station_id: params[:start_station_id], end_station_id: params[:end_station_id])
Можно использовать `slice`: `Ticket.new(params.slice(:train_id, :start_station_id, :end_station_id))`.

2016-12-21 20:49 UTC, psylone commented on app/models/ticket.rb
> +  belongs_to :end_station, class_name: RailwayStation
Не помешают валидации на ФИО и паспорт.

2016-12-21 20:49 UTC, psylone commented on app/helpers/cars_helper.rb
> +  class CarsFormBuilder < ActionView::Helpers::FormBuilder
> В Rails 5 есть стандартное место для пользовательских FormBuilder-ов?

Не думаю.

Не вижу ничего дурного в том чтобы использовать вложенность: `CarsHelper::CarsFormBuilder`. Вариант с `load_paths` тоже подойдёт, обычно его и используют.

2016-12-22 08:00 UTC, askrynnikov commented on app/views/searches/show.html.erb
> +              <%= form_tag new_ticket_path, method: :get do %>
Вижу что широко используется.
Даже пишут как правильно из готовить
[popular-mistakes-when-using-nested-forms](https://makandracards.com/makandra/1346-popular-mistakes-when-using-nested-forms)
Вывод какой? Никогда не делать вложенных форм?

2016-12-22 08:03 UTC, askrynnikov commented on app/helpers/cars_helper.rb
> +  class CarsFormBuilder < ActionView::Helpers::FormBuilder
Ok! Оставляю как вложенный класс

2016-12-22 08:17 UTC, askrynnikov commented on app/controllers/railway_stations_controller.rb
>      params.require(:railway_station).permit(:title)
Все работает. Чего может не хватать?

2016-12-22 08:18 UTC, askrynnikov commented on config/routes.rb
> +    resources :cars, shallow: true
Вагоны создаются и отдельно и через поезд. Почему возник вопрос?

2016-12-22 08:32 UTC, askrynnikov commented on app/controllers/tickets_controller.rb
> +    @ticket = Ticket.new(train_id: params[:train_id], start_station_id: params[:start_station_id], end_station_id: params[:end_station_id])
Рельсы расширили стандартный Hash. Прикольно. Спасибо.

2016-12-22 08:40 UTC, askrynnikov commented on app/models/ticket.rb
> +  belongs_to :end_station, class_name: RailwayStation
Ok!

2016-12-22 08:41 UTC, askrynnikov commented
Done.

2016-12-22 11:18 UTC, psylone commented on config/routes.rb
> +    resources :cars, shallow: true
Очевидно, потому что у меня не получилось создать вагон у поезда через веб-интерфейс )

2016-12-22 12:30 UTC, askrynnikov commented on config/routes.rb
> +    resources :cars, shallow: true
заходим в поезд /trains/1
внизу вагоны поезда и ссылка "Добавить вагон" и она работает )

2016-12-22 14:13 UTC, psylone commented on app/controllers/railway_stations_controller.rb
>      params.require(:railway_station).permit(:title)
Атрибута `arrival`?

2016-12-22 14:14 UTC, psylone commented on app/controllers/tickets_controller.rb
> +    @ticket = Ticket.new(train_id: params[:train_id], start_station_id: params[:start_station_id], end_station_id: params[:end_station_id])
В `params` не хэш. А так да, есть дополнительные методы для хэша в ActiveSupport.

2016-12-22 14:15 UTC, psylone commented on app/views/searches/show.html.erb
> +              <%= form_tag new_ticket_path, method: :get do %>
Спецификация HTML и вложенные формы Rails это не одно и тоже.

2016-12-22 17:16 UTC, askrynnikov commented on app/controllers/railway_stations_controller.rb
>      params.require(:railway_station).permit(:title)
Нет, он здесь не нужен.
см. 58-60 строку в routes_controller.rb 
```
  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
```
Оно?

2016-12-22 22:07 UTC, psylone commented on app/controllers/railway_stations_controller.rb
>      params.require(:railway_station).permit(:title)
Нет. Суть в том что при обновлении даты прибытия или порядка станции в маршруте данные не сохраняются у меня.

2016-12-22 22:22 UTC, psylone commented on app/controllers/railway_stations_controller.rb
>      params.require(:railway_station).permit(:title)
Это из-за формата полей отправления и прибытия в поле формы, проверь.

2016-12-22 22:27 UTC, psylone commented on config/routes.rb
> +    resources :cars, shallow: true
Ссылка-то работает, а вот при создании вагона у меня такая картина:

![Alt text](https://monosnap.com/file/z3cXluSM11G3NCbdQgI7kBUHuqd5Qo.png)

2016-12-22 22:33 UTC, psylone commented on app/models/search.rb
> +  accepts_nested_attributes_for :tickets
Этот метод в ActiveRecord находится, не в ActiveModel. У тебя здесь нет ошибки?

2016-12-23 06:48 UTC, askrynnikov commented on config/routes.rb
> +    resources :cars, shallow: true
Ты забегаешь вперед :) мы еще не проходили JS 
Конечно нужно делать валидацию поля во представлении, чтобы nil не отправлять (и при выборе типа вагона показывать только нужные типы мест)
А пока убрал проверки 
  `validates :seat_places, presence: true, numericality: { only_integer: true }`
теперь сохраняет nil и идет дальше без ошибки

какие еще могут быть варианты решения?

2016-12-23 07:08 UTC, askrynnikov commented on app/models/search.rb
> +  accepts_nested_attributes_for :tickets
Это экспериментировал чтобы вложенная форма заработала.
Убрал.

2016-12-23 11:02 UTC, psylone commented on config/routes.rb
> +    resources :cars, shallow: true
Здесь суть в том что хэлпер определения URL не находится. Посмотри подробней сообщение об ошибке.

2016-12-23 17:02 UTC, askrynnikov commented on config/routes.rb
> +    resources :cars, shallow: true
) с четвертого раза дошло, исправил.

2016-12-23 17:39 UTC, askrynnikov commented on app/controllers/railway_stations_controller.rb
>      params.require(:railway_station).permit(:title)
> из-за формата полей отправления 

непонятно, в `datetime_field_tag` негде задать формат 

решил проблему так: в `app/models/railway_station.rb` убрал `||=`
стало `@station_route = railway_stations_routes.where(route: route).first`
после сохранения данные обновляются

2016-12-24 13:10 UTC, psylone commented on config/routes.rb
> +    resources :cars, shallow: true
💪

2016-12-24 14:01 UTC, psylone approved these changes

2016-12-24 14:01 UTC, psylone commented on app/controllers/cars_controller.rb
> +    @train = Train.find(params[:train_id]) if params[:train_id]
Можно использовать `find_by`:

```ruby
def set_train
  @train = Train.find_by(id: params[:train_id])
end
```

2016-12-24 14:01 UTC, psylone commented on app/controllers/cars_controller.rb
>    def create
Сложный получился метод. В идеале, в Контроллере кроме назначения переменных и вызова редиректов больше ничего не должно быть. В крайнем случае стоит разбить этот метод на несколько. А ещё лучше создать класс `CarsInteractor` или `CarsManager` или `CarsService`, короче обычный Ruby класс который будет инкапсулировать в себе всю эту логику. Такой класс можно разместить в новом слое приложения в каталоге `app/interactors` или `app/services`.

2016-12-24 14:01 UTC, psylone commented on app/models/railway_station.rb
> +    railway_station_route.update(params.slice(:station_order,
Здесь возникает: `ActiveModel::ForbiddenAttributesError`.

2016-12-27 12:16 UTC, askrynnikov commented on app/controllers/cars_controller.rb
>    def create
Как эта инкапсуляция должна выглядеть, как здесь делать слабосвязанный код?
Можно пример кода сервисного класса?

2016-12-29 11:02 UTC, merged